services:
  - type: web
    name: herramienta-maplestory-imanity-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: FIREBASE_WEB_API_KEY
        value: "AIzaSyCylI-FadSqtTED7fQH6-Z4LWMIkbOfbAI"
      - key: REGISTER_TOKEN
        sync: false
