mutation UpsertCurrentUser(
  $username: String!
  $displayName: String
  $email: String
) @auth(level: USER) {
  appUser_upsert(data: {
    id_expr: "auth.uid"
    username: $username
    displayName: $displayName
    email: $email
    updatedAt_expr: "request.time"
  })
}

query GetCurrentUser @auth(level: USER) {
  appUser(key: { id_expr: "auth.uid" }) {
    id
    username
    displayName
    email
    createdAt
    updatedAt
  }
}
